#!/bin/zsh

set -e -u

cd `dirname $0`

_out="libmini.dylib"

_flg="\
    -framework AppKit \
    -framework JavaScriptCore \
    -dynamiclib \
    -fobjc-arc \
    -std=c++17 \
    -Os"

_inc="\
    -Iappsrc \
    -Ihost_osx/mini_osx \
    -Ihost/mini_mac"

_src="\
    appsrc/c*.cpp \
    appsrc/d*.cpp \
    appsrc/m*.cpp \
    appsrc/r*.cpp \
    host_osx/mini_osx/*.mm \
    host/mini_mac/*.mm"

function build() {
    local plat=$1
    local ddir=$2

    mkdir -p $ddir
    rm    -f $ddir/$_out

    clang++ \
        -install_name $_out \
        -o $ddir/$_out \
        -target $plat \
        $_flg \
        $_inc \
        $_src
}

function main() {
    build "arm64-apple-macosx12"  "BUILD/osx_arm64"
    build "x86_64-apple-macosx12" "BUILD/osx_x64"
}

main
