#!/bin/bash

set -e -u

cd `dirname $0`

exe_nam="mini"
obj_dir="objs"
hdr_inc="-I../appsrc -I../host/mini_pc"
cc_dirs="  ../appsrc   ../host/mini_pc mini_linux"
dpd_cmd="c++ -MM $hdr_inc -MT"
obj_cmd="c++ -c  $hdr_inc --std=c++17 -o"
exe_cmd="c++ -o  $exe_nam --std=c++17"

# generate the temporary object file directory.
mkdir -p $obj_dir

# generate the makefile:
function rewrit_mf() { echo -e -n "$1"  > makefile; }
function append_mf() { echo -e -n "$1" >> makefile; }

function every_src() {
    for src in `find $cc_dirs -iname *.cpp`; do
        local obj="$obj_dir/`basename $src .cpp`.o"
        $1 $obj $src
    done
}

function obj_itm_to_mf() {
    append_mf " $1"
}
function obj_dpd_to_mf() {
    append_mf  "`$dpd_cmd $1 $2`\n"
    append_mf "\t$obj_cmd $1 $2\n"
}

rewrit_mf "$exe_nam:"
every_src obj_itm_to_mf
append_mf "\n"

append_mf "\t$exe_cmd"
every_src obj_itm_to_mf
append_mf "\n"

every_src obj_dpd_to_mf
