#!/bin/bash

set -e -u

cd `dirname $0`

_outexe="mini"
_objdir="objs"

_flg="\
    -std=c++17 \
    -m64 \
    -Os"

_inc="\
    -I../appsrc \
    -I../host/mini_pc \
    -Imini_linux"

_src="\
    ../appsrc \
    ../host/mini_pc \
    mini_linux"

function write_makefile() {
    echo -e -n "$1" >> makefile
}

function add_obj_path() {
    local obj=$1

    write_makefile " $obj"
}

function add_obj_make() {
    local obj=$1
    local cxx=$2

    write_makefile " `c++ $_inc -MM     -MT $obj $cxx`\n"
    write_makefile "\tc++ $_inc $_flg -c -o $obj $cxx \n"
}

function for_every_csrc() {
    local callback=$1
    for cxx in `find $_src -iname *.cpp`; do
        local obj="$_objdir/`basename $cxx .cpp`.o"
        $callback $obj $cxx
    done
}

function main() {
    rm makefile
    rm -rf $_objdir
    mkdir  $_objdir

    # final target:
    write_makefile "$_outexe:"
    for_every_csrc add_obj_path
    write_makefile "\n"

    write_makefile "\tc++ -o $_outexe"
    for_every_csrc add_obj_path
    write_makefile "\n"

    # obj files.
    for_every_csrc add_obj_make
}

main
